"""Add document_id to Conversation

Revision ID: abc123def456
Revises: 
Create Date: 2026-09-13 07:20:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'abc123def456'
down_revision = None  # Add appropriate down_revision if needed
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conversations_document_id'), 'conversations', ['document_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_document_id'), table_name='conversations')
    op.drop_column('conversations', 'document_id')
    # ### end Alembic commands ###
